### PR TITLE
Added note to readme about cartesian pose definition

### PR DESCRIPTION
**Pull request by mjsobrep**

### CODE REVIEW

**Comment by mjsobrep** [comment]
Lol, @varunagrawal @ToniCvitanic this is still open?

**Comment by varunagrawal** [comment]
Minor update. Merging.

**Comment by varunagrawal** [comment]
Damn I need write access to this as well! What is happening? 😢

**Comment by ToniCvitanic** [comment]
@varunagrawal I just gave you write access to all our github.com repositories. For some reason, you only had read.

**Pull request merged**
